version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server:
    build: ./server
    container_name: server_d
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/Apartment-Finder
      - REDIS_URL=redis://redis:6379
    command: >
      sh -c "node ./src/seed.js && npm start"
  react-client:
    build: ./react-client
    container_name: react-client_d
    ports:
      - "5173:5173"
      - "9229:9229"
    environment:
      - REACT_APP_SERVER=http://server:3000
    env_file:
      - ./react-client/.env
    stdin_open: true
    tty: true
volumes:
  mongo-data:
  redis-data:
